// ignore_for_file: public_member_api_docs
import 'dart:ui';

import 'package:deriv_chart/deriv_chart.dart';
import 'package:deriv_chart/src/theme/painting_styles/candle_style.dart';
import 'package:deriv_chart/src/theme/painting_styles/grid_style.dart';
import 'package:deriv_chart/src/theme/painting_styles/line_style.dart';
import 'package:deriv_chart/src/theme/painting_styles/marker_style.dart';
import 'package:flutter/material.dart';

/// An interface for the Chart's theme.
///
/// Any app which wants to define the chart's theme should pass an implementation of this interface.
abstract class ChartTheme {
  String get fontFamily;

  Color get brandCoralColor;

  Color get brandGreenishColor;

  Color get brandOrangeColor;

  Color get accentRedColor;

  Color get accentGreenColor;

  Color get accentYellowColor;

  Color get base01Color;

  Color get base02Color;

  Color get base03Color;

  Color get base04Color;

  Color get base05Color;

  Color get base06Color;

  Color get base07Color;

  Color get base08Color;

  double get margin04;

  double get margin08;

  double get margin12;

  double get margin16;

  double get margin24;

  double get margin32;

  double get borderRadius04;

  double get borderRadius08;

  double get borderRadius16;

  double get borderRadius24;

  TextStyle get caption2;

  GridStyle get gridStyle;

  TextStyle get subheading;

  TextStyle get body2;

  TextStyle get body1;

  TextStyle get title;

  /// The style of the current tick indicator
  HorizontalBarrierStyle get currentTickStyle;

  /// The painting styles of candlestick chart
  CandleStyle get candleStyle;

  /// The painting styles of line chart
  LineStyle get lineStyle;

  /// The painting styles of markers
  MarkerStyle get markerStyle;

  /// The painting styles horizontal barriers
  HorizontalBarrierStyle get horizontalBarrierStyle;

  /// The painting styles vertical barriers
  VerticalBarrierStyle get verticalBarrierStyle;

  /// The style of text is generated by calling this function,
  ///
  /// The [textStyle] argument must not be null, and if null is passed, an
  /// ArgumentError will be thrown
  ///
  /// The [color] may be null or un-passed, in that case, a default value will
  /// be assigned to it
  TextStyle textStyle({
    @required TextStyle textStyle,
    Color color,
  });
}
